### ISSUE TITLE
Likelihood test with constant-expression model

### ISSUE THREAD

**Issue by floklimm** [kieranrcampbell/switchde#7]
In the paper, you mention that one can compare the likelihood with a nested constant-expression model.

Is this implemented?

**Comment by kieranrcampbell** [comment]
Hi @floklimm 

The output includes p and q values for each gene that are the results of the likelihood ratio tests wrt a constant expression model (if I remember correctly -- it's been a while!)

Kieran

**Comment by floklimm** [comment]
Thanks; that makes sense!
